site_name: 高性价比人生指南
site_description: 高性价比人生指南
site_author: shutouyabo
site_url: https://rensheng.zhihu.blog/
repo_name: 高性价比人生指南
repo_url: https://github.com/shutouyabo/gaoxingjiabirenshengzhinan
copyright: Copyright &copy; 2026 <a href="https://rensheng.zhihu.blog/" target="_blank" rel="noopener noreferrer">高性价比人生指南</a>

theme:
  name: 'material'
  language: 'zh'
  font: false
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  icon:
    logo: fontawesome/brands/linux
    repo: octicons/mark-github-16
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - markdown.extensions.def_list
  - toc:
      permalink: true

extra:
  social:
    - icon: octicons/globe-16
      link: https://v6.51.la/land/LLAxEC8pfvLRyqQZ
    - icon: octicons/mark-github-16
      link: https://github.com/shutouyabo
  analytics:
    provider: google
    property: G-Q8WSZQS8E1

extra_css:
  - 'css/extra.css'
  - 'https://101.lug.ustc.edu.cn/_extra/roboto.css'
  - 'https://101.lug.ustc.edu.cn/_extra/roboto-mono/stylesheet.css'

nav:
    - 前言: "index.md"
    - 01-不要早死（42）: "01-不要早死.md"
    - 02-不要慢慢死（42）: "02-不要慢慢死.md"
    - 03-不要浪费精力（24）: "03-不要浪费精力.md"
    - 04-不要浪费时间（18）: "04-不要浪费时间.md"
    - 05-不要浪费钱（45）: "05-不要浪费钱.md"
    - 06-反面清单（29）: "06-反面清单.md"
    - 07-没钱的时候怎么活（22）: "07-没钱的时候怎么活.md"
    - 08-别把自己搭进去（46）: "08-别把自己搭进去.md"
    - 09-普通人容易踩的法律红线（26）: "09-普通人容易踩的法律红线.md"
    - 10-恋爱和结婚划不划算（20）: "10-恋爱和结婚划不划算.md"
    - 11-程序员和技术人容易踩的红线（19）: "11-程序员和技术人容易踩的红线.md"
    - 12-创业与做生意（24）: "12-创业与做生意.md"
    - 13-紧急情况（44）: "13-紧急情况.md"
    - 14-账号与信息安全（10）: "14-账号与信息安全.md"
    - 15-租房与买房（9）: "15-租房与买房.md"
    - 16-得了慢性病之后怎么活（9）: "16-得了慢性病之后怎么活.md"
    - 17-家里有老人（9）: "17-家里有老人.md"
    - 18-养孩子划不划算（6）: "18-养孩子划不划算.md"
    - 19-在职离职和工伤（18）: "19-在职离职和工伤.md"
    - 20-刚出生的孩子怎么带（13）: "20-刚出生的孩子怎么带.md"
    - 21-出国旅行与境外安全（11）: "21-出国旅行与境外安全.md"
    - 22-怎么放松（10）: "22-怎么放松.md"
    - 23-学什么技能划算（23）: "23-学什么技能划算.md"
    - 24-看病（12）: "24-看病.md"
    - 25-人走了以后要办什么（10）: "25-人走了以后要办什么.md"
    - 26-做一个网站或平台（11）: "26-做一个网站或平台.md"
    - 27-怀孕和生产（16）: "27-怀孕和生产.md"
    - 28-别为了外形把身体搞坏（9）: "28-别为了外形把身体搞坏.md"
    - 29-遭遇重大打击之后（13）: "29-遭遇重大打击之后.md"
    - 30-上学以后的孩子（18）: "30-上学以后的孩子.md"
    - 31-十八岁之后有哪几条路（16）: "31-十八岁之后有哪几条路.md"
    - 32-出国留学（10）: "32-出国留学.md"
    - 33-残疾之后怎么活（20）: "33-残疾之后怎么活.md"
    - 34-家里的常备药别吃出事（11）: "34-家里的常备药别吃出事.md"

