site_name: 高性价比人生指南
site_url: https://rensheng.zhihu.blog/
site_author: shutouyabo
site_description: >-
  gaoxingjiabirenshengzhinan

repo_name: 高性价比人生指南
repo_url: https://github.com/shutouyabo/gaoxingjiabirenshengzhinan

copyright: Copyright &copy; 2026 <a href="https://rensheng.zhihu.blog/" target="_blank" rel="noopener noreferrer">高性价比人生指南</a>



theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  apple-touch-icon-precomposed: images/mobile_icon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - i18n:
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true

  - search:
      lang:
        - zh
  - encryptcontent:
      remember_password: true        # 开启记住密码 关闭false 开启true
      default_expire_delay: 1      # 过期时间，单位小时；0.002778=10秒钟
      session_storage: true
  - git-revision-date:
  - minify:
      minify_html: true
  - open-in-new-tab:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://v6.51.la/land/L0ZDlWY6HhH0NxKi
  analytics:
    provider: google
    property: G-KJB4RXSKZG

nav:
  - 前言: "index.md"
  - 01-不要早死（36）: "01-不要早死.md"
  - 02-不要慢慢死: "02-不要慢慢死.md"
  - 03-不要浪费精力: "03-不要浪费精力.md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
  - : ".md"
